net.minecraftforge.gradle.merge-source-sets=true

minecraft_version=26.1
minecraft_version_range=[26.1,27.1)
forge_version=62.0.9
forge_version_range=[62.0.5,)
loader_version_range=[62,)

mod_id=sodiumpp
mod_name=sodiumpp
mod_license=MIT
# mod_version = 0.0.0 - loaded from common directory
mod_group_id=com.dimsteams.sodiumpp
mod_authors=dimsteams, SomeRandomDude-a
mod_description=Open http://localhost:5005/ in your browser to access mod settings.\nIf you run multiple minecraft instances, use http://localhost:5006/, http://localhost:5007/ and so on.\nYou can find tutorial videos on curseforge page: https://www.curseforge.com/minecraft/mc-mods/sodiumpp\nSource code: https://github.com/dimsteams/sodiumpp